### PR TITLE
Fix open and OWE networks

### PR DESCRIPTION
**Pull request by chuckwagoncomputing**
Trying to connect to an open network showed the "Unknown security type" error.
I also noticed while reading the code that OWE networks would still ask for a password, and I tried to fix that, but I haven't been able to test it because NM isn't reporting my network as OWE when I enable it on my router. I'm not sure if the wifi on my Biqu CB1 doesn't support it or what.

### CODE REVIEW

**Comment by alfrix** [comment]
This doesn't seem to be correct, i will do a quick fixup

**Comment by chuckwagoncomputing** [comment]
Good call on the OWE, but you haven't fixed the issue with open networks, I just tested master and am getting the "Unknown security type" error.

**Comment by alfrix** [comment]
> Good call on the OWE, but you haven't fixed the issue with open networks, I just tested master and am getting the "Unknown security type" error.

since i don't have anything with support of owe, i cannot test it at the moment

i suggest you add in get_networks:
below `all_aps = [AccessPoint(result) for result in self.wlan_device.access_points]`
```
for ap in all_aps:
    logging.debug(f"SSID: {ap.ssid}")
    logging.debug(f"AP-RSN FLAGS: {ap.rsn_flags}")
    logging.debug(f"AP-WPA FLAGS: {ap.wpa_flags}")
    logging.debug(f"AP     FLAGS: {ap.flags}")
```
to check if the flags of the ssid are properly reported or maybe there is an issue in detection

**Comment by chuckwagoncomputing** [comment]
OWE is not being properly reported by NetworkManager; ignore that for now.

The bigger issue is that normal open networks (non-OWE) aren't working.
add_network in sdbus_nm.py checks all security types, and finding none, returns an error of "Unknown security type". This is why I indented all those if statements to be within the `if security_type != "Open":` if statement scope.

**Comment by alfrix** [comment]
in theory one could define the open network a bit differently like:
```diff
                 "ssid": ("ay", ssid.encode("utf-8")),
+                "security": ("s", "802-11-wireless-security"),
             },
             "ipv4": {"method": ("s", "auto")},
             "ipv6": {"method": ("s", "auto")},
         }
 
-        if security_type != "Open":
-            properties["802-11-wireless"]["security"] = (
-                "s",
-                "802-11-wireless-security",
-            )
-        if "WPA-PSK" in security_type:
+        if security_type == "Open":
+            properties["802-11-wireless-security"] = {
+                "key-mgmt": ("s", "none"),
+            }
+        elif "WPA-PSK" in security_type:
             properties["802-11-wireless-security"] = {

```

**Comment by chuckwagoncomputing** [comment]
That doesn't seem to work, but I haven't yet figured out why not. I'm guessing something is checking for the presence or values of the "security" field.
It no longer displays the error; it says it's associating, but never shows that it is connected. There are no errors in journalctl.

**Comment by chuckwagoncomputing** [comment]
When I said "There are no errors in journalctl", I was looking at KlipperScreen messages only, which was a little stupid. NetworkManager gives us some output:
```
Jul 21 08:54:26 BTT-CB1 KlipperScreen-start.sh[1086]: 20240721 08:54:26,748 [screen.py:show_popup_message] - echo: ChuckWagon Computing
Jul 21 08:54:26 BTT-CB1 KlipperScreen-start.sh[1086]: Starting WiFi Association
Jul 21 08:54:26 BTT-CB1 NetworkManager[450]: <info>  [1721570066.7667] device (wlan0): Activation: starting connection 'ChuckWagon Computing' (957e9517-18fb-403e-90cc-495f8a17b225)
Jul 21 08:54:26 BTT-CB1 NetworkManager[450]: <info>  [1721570066.7673] audit: op="connection-activate" uuid="957e9517-18fb-403e-90cc-495f8a17b225" name="ChuckWagon Computing" pid=1086 uid=1000 result="success"
Jul 21 08:54:26 BTT-CB1 NetworkManager[450]: <info>  [1721570066.7679] device (wlan0): state change: disconnected -> prepare (reason 'none', sys-iface-state: 'managed')
Jul 21 08:54:26 BTT-CB1 NetworkManager[450]: <info>  [1721570066.7727] device (wlan0): state change: prepare -> config (reason 'none', sys-iface-state: 'managed')
Jul 21 08:54:26 BTT-CB1 NetworkManager[450]: <info>  [1721570066.7743] device (wlan0): Activation: (wifi) access point 'ChuckWagon Computing' has security, but secrets are required.
Jul 21 08:54:26 BTT-CB1 NetworkManager[450]: <info>  [1721570066.7744] device (wlan0): state change: config -> need-auth (reason 'none', sys-iface-state: 'managed')
Jul 21 08:54:26 BTT-CB1 NetworkManager[450]: <warn>  [1721570066.7768] device (wlan0): no secrets: No agents were available for this request.
Jul 21 08:54:26 BTT-CB1 NetworkManager[450]: <info>  [1721570066.7769] device (wlan0): state change: need-auth -> failed (reason 'no-secrets', sys-iface-state: 'managed')
Jul 21 08:54:26 BTT-CB1 NetworkManager[450]: <warn>  [1721570066.7792] device (wlan0): Activation: failed for connection 'ChuckWagon Computing'
Jul 21 08:54:26 BTT-CB1 NetworkManager[450]: <info>  [1721570066.7804] device (wlan0): state change: failed -> disconnected (reason 'none', sys-iface-state: 'managed')
```

**Pull request closed without merging**
