### PR TITLE
Update Hungarian Language

### PR DESCRIPTION
**Pull request by AntoszHUN**
Hungarian Language update.

 - Fixing a small typo.
 
Signed-off-by: AntoszHUN [zsikaiantal@icloud.com]

### CODE REVIEW

**Comment by alfrix** [comment]
Thank you

Note: you can also do the translation on https://hosted.weblate.org/projects/klipperscreen/klipperscreen/

**Comment by AntoszHUN** [comment]
> Thank you
> 
> Note: you can also do the translation on https://hosted.weblate.org/projects/klipperscreen/klipperscreen/

Thanks, but I'd rather not. I also translated the Klipper website into Hungarian there. in half a year, the repairs have not yet been made.

**Comment by alfrix** [comment]
> > Thank you
> > Note: you can also do the translation on https://hosted.weblate.org/projects/klipperscreen/klipperscreen/
> 
> Thanks, but I'd rather not. I also translated the Klipper website into Hungarian there. in half a year, the repairs have not yet been made.

Klipper and KlipperScreen are separated projects with different maintainers

i do regularly merge the weblate PRs: https://github.com/KlipperScreen/KlipperScreen/pulls?q=is%3Apr+Translations+update+from+Hosted+Weblate

there are many benefits prs from weblate can contain the work of multiple translators, saving some time, it is more collaborative, as more than one translator can work at the same time on the same language, it has a glossary etc.

---

In regards of the Klipper website issue, i see that you translated most of it with parity to other languages that are active, the translation is so complete that should be enabled in the website (Great work!)

after a couple of minutes of research:
for the translation to enabled you need to add it to the [active_translations](https://github.com/Klipper3d/klipper-translations/blob/translations/active_translations) file because the [build script](https://github.com/Klipper3d/klipper-translations/blob/27e1d5c9a9ca4481a2d9de29801dbd56b904eacc/docs/_klipper3d/build-translations.sh#L9) looks for it

so you should make a pr to https://github.com/Klipper3d/klipper-translations updating the file, that should raise the awareness of the maintainers over there

**Comment by alfrix** [comment]
in the contributing doc for translations it does mention the active_translations file and other stuff:
https://github.com/Klipper3d/klipper-translations/blob/translations/docs/CONTRIBUTING.md#contributing-to-klipper-translations

**Comment by AntoszHUN** [comment]
> > > Thank you
> > > Note: you can also do the translation on https://hosted.weblate.org/projects/klipperscreen/klipperscreen/
> > 
> > 
> > Thanks, but I'd rather not. I also translated the Klipper website into Hungarian there. in half a year, the repairs have not yet been made.
> 
> Klipper and KlipperScreen are separated projects with different maintainers
> 
> i do regularly merge the weblate PRs: https://github.com/KlipperScreen/KlipperScreen/pulls?q=is%3Apr+Translations+update+from+Hosted+Weblate
> 
> there are many benefits prs from weblate can contain the work of multiple translators, saving some time, it is more collaborative, as more than one translator can work at the same time on the same language, it has a glossary etc.
> 
> In regards of the Klipper website issue, i see that you translated most of it with parity to other languages that are active, the translation is so complete that should be enabled in the website (Great work!)
> 
> after a couple of minutes of research: for the translation to enabled you need to add it to the [active_translations](https://github.com/Klipper3d/klipper-translations/blob/translations/active_translations) file because the [build script](https://github.com/Klipper3d/klipper-translations/blob/27e1d5c9a9ca4481a2d9de29801dbd56b904eacc/docs/_klipper3d/build-translations.sh#L9) looks for it
> 
> so you should make a pr to https://github.com/Klipper3d/klipper-translations updating the file, that should raise the awareness of the maintainers over there

All right. Thanks!

**Pull request merged**
