### PR TITLE
doc: update git url

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Comment by alfrix** [comment]
Thank you

**Comment by thijstriemstra** [comment]
@alfrix what happened to the `jordanruthe/KlipperScreen` repository? why did it change?

**Comment by alfrix** [comment]
it was moved to an org, Jordan had already created it, the org should be more manageable if more people want to be part of the team

**Comment by thijstriemstra** [comment]
> it was moved to an org, Jordan had already created it, the org should be more manageable if more people want to be part of the team

I see. But it looks like all of @jordanruthe commits moved to your name, right?

**Comment by alfrix** [comment]
> > it was moved to an org, Jordan had already created it, the org should be more manageable if more people want to be part of the team
> 
> I see. But it looks like all of @jordanruthe commits moved to @alfrix, right? why?

all the history was preserved as it should, it's just that Jordan has not made any commits since 2022:

https://github.com/KlipperScreen/KlipperScreen/commits?author=jordanruthe

**Comment by thijstriemstra** [comment]
I guess it's been a while since I updated my printer! Sorry for being.. suspicious.

**Pull request merged**
