### PR TITLE
Refactoring: clean freq selection algorithm

### PR DESCRIPTION
**Pull request by johncooler**

### CODE REVIEW

**Comment by alfrix** [comment]
this is not the same. your code need to pass this unit test:

```

class TestWifiChannels(unittest.TestCase):
    def test_lookup_2412(self):
        channel = WifiChannels.lookup('2412')
        self.assertEqual(channel, ('2.4', '1'))

    def test_lookup_2417(self):
        channel = WifiChannels.lookup('2417')
        self.assertEqual(channel, ('2.4', '2'))

    def test_lookup_2422(self):
        channel = WifiChannels.lookup('2422')
        self.assertEqual(channel, ('2.4', '3'))

    def test_lookup_2427(self):
        channel = WifiChannels.lookup('2427')
        self.assertEqual(channel, ('2.4', '4'))

    def test_lookup_2432(self):
        channel = WifiChannels.lookup('2432')
        self.assertEqual(channel, ('2.4', '5'))

    def test_lookup_2437(self):
        channel = WifiChannels.lookup('2437')
        self.assertEqual(channel, ('2.4', '6'))

    def test_lookup_2442(self):
        channel = WifiChannels.lookup('2442')
        self.assertEqual(channel, ('2.4', '7'))

    def test_lookup_2447(self):
        channel = WifiChannels.lookup('2447')
        self.assertEqual(channel, ('2.4', '8'))

    def test_lookup_2452(self):
        channel = WifiChannels.lookup('2452')
        self.assertEqual(channel, ('2.4', '9'))

    def test_lookup_2457(self):
        channel = WifiChannels.lookup('2457')
        self.assertEqual(channel, ('2.4', '10'))

    def test_lookup_2462(self):
        channel = WifiChannels.lookup('2462')
        self.assertEqual(channel, ('2.4', '11'))

    def test_lookup_2467(self):
        channel = WifiChannels.lookup('2467')
        self.assertEqual(channel, ('2.4', '12'))

    def test_lookup_2472(self):
        channel = WifiChannels.lookup('2472')
        self.assertEqual(channel, ('2.4', '13'))

    def test_lookup_2484(self):
        channel = WifiChannels.lookup('2484')
        self.assertEqual(channel, ('2.4', '14'))

    def test_lookup_5035(self):
        channel = WifiChannels.lookup('5035')
        self.assertEqual(channel, ('5', '7'))

    def test_lookup_5040(self):
        channel = WifiChannels.lookup('5040')
        self.assertEqual(channel, ('5', '8'))

    def test_lookup_5045(self):
        channel = WifiChannels.lookup('5045')
        self.assertEqual(channel, ('5', '9'))

    def test_lookup_5055(self):
        channel = WifiChannels.lookup('5055')
        self.assertEqual(channel, ('5', '11'))

    def test_lookup_5060(self):
        channel = WifiChannels.lookup('5060')
        self.assertEqual(channel, ('5', '12'))

    def test_lookup_5080(self):
        channel = WifiChannels.lookup('5080')
        self.assertEqual(channel, ('5', '16'))

    def test_lookup_5170(self):
        channel = WifiChannels.lookup('5170')
        self.assertEqual(channel, ('5', '34'))

    def test_lookup_5180(self):
        channel = WifiChannels.lookup('5180')
        self.assertEqual(channel, ('5', '36'))

    def test_lookup_5190(self):
        channel = WifiChannels.lookup('5190')
        self.assertEqual(channel, ('5', '38'))

    def test_lookup_5200(self):
        channel = WifiChannels.lookup('5200')
        self.assertEqual(channel, ('5', '40'))

    def test_lookup_5210(self):
        channel = WifiChannels.lookup('5210')
        self.assertEqual(channel, ('5', '42'))

    def test_lookup_5220(self):
        channel = WifiChannels.lookup('5220')
        self.assertEqual(channel, ('5', '44'))

    def test_lookup_5230(self):
        channel = WifiChannels.lookup('5230')
        self.assertEqual(channel, ('5', '46'))

    def test_lookup_5240(self):
        channel = WifiChannels.lookup('5240')
        self.assertEqual(channel, ('5', '48'))

    def test_lookup_5260(self):
        channel = WifiChannels.lookup('5260')
        self.assertEqual(channel, ('5', '52'))

    def test_lookup_5280(self):
        channel = WifiChannels.lookup('5280')
        self.assertEqual(channel, ('5', '56'))

    def test_lookup_5300(self):
        channel = WifiChannels.lookup('5300')
        self.assertEqual(channel, ('5', '60'))

    def test_lookup_5320(self):
        channel = WifiChannels.lookup('5320')
        self.assertEqual(channel, ('5', '64'))

    def test_lookup_5500(self):
        channel = WifiChannels.lookup('5500')
        self.assertEqual(channel, ('5', '100'))

    def test_lookup_5520(self):
        channel = WifiChannels.lookup('5520')
        self.assertEqual(channel, ('5', '104'))

    def test_lookup_5540(self):
        channel = WifiChannels.lookup('5540')
        self.assertEqual(channel, ('5', '108'))

    def test_lookup_5560(self):
        channel = WifiChannels.lookup('5560')
        self.assertEqual(channel, ('5', '112'))

    def test_lookup_5580(self):
        channel = WifiChannels.lookup('5580')
        self.assertEqual(channel, ('5', '116'))

    def test_lookup_5600(self):
        channel = WifiChannels.lookup('5600')
        self.assertEqual(channel, ('5', '120'))

    def test_lookup_5620(self):
        channel = WifiChannels.lookup('5620')
        self.assertEqual(channel, ('5', '124'))

    def test_lookup_5640(self):
        channel = WifiChannels.lookup('5640')
        self.assertEqual(channel, ('5', '128'))

    def test_lookup_5660(self):
        channel = WifiChannels.lookup('5660')
        self.assertEqual(channel, ('5', '132'))

    def test_lookup_5680(self):
        channel = WifiChannels.lookup('5680')
        self.assertEqual(channel, ('5', '136'))

    def test_lookup_5700(self):
        channel = WifiChannels.lookup('5700')
        self.assertEqual(channel, ('5', '140'))

    def test_lookup_5720(self):
        channel = WifiChannels.lookup('5720')
        self.assertEqual(channel, ('5', '144'))

    def test_lookup_5745(self):
        channel = WifiChannels.lookup('5745')
        self.assertEqual(channel, ('5', '149'))

    def test_lookup_5765(self):
        channel = WifiChannels.lookup('5765')
        self.assertEqual(channel, ('5', '153'))

    def test_lookup_5785(self):
        channel = WifiChannels.lookup('5785')
        self.assertEqual(channel, ('5', '157'))

    def test_lookup_5805(self):
        channel = WifiChannels.lookup('5805')
        self.assertEqual(channel, ('5', '161'))

    def test_lookup_5825(self):
        channel = WifiChannels.lookup('5825')
        self.assertEqual(channel, ('5', '165'))

    def test_lookup_4915(self):
        channel = WifiChannels.lookup('4915')
        self.assertEqual(channel, ('5', '183'))

    def test_lookup_4920(self):
        channel = WifiChannels.lookup('4920')
        self.assertEqual(channel, ('5', '184'))

    def test_lookup_4925(self):
        channel = WifiChannels.lookup('4925')
        self.assertEqual(channel, ('5', '185'))

    def test_lookup_4935(self):
        channel = WifiChannels.lookup('4935')
        self.assertEqual(channel, ('5', '187'))

    def test_lookup_4940(self):
        channel = WifiChannels.lookup('4940')
        self.assertEqual(channel, ('5', '188'))

    def test_lookup_49450(self):
        channel = WifiChannels.lookup('4945')
        self.assertEqual(channel, ('5', '189'))

    def test_lookup_4960(self):
        channel = WifiChannels.lookup('4960')
        self.assertEqual(channel, ('5', '192'))

    def test_lookup_4980(self):
        channel = WifiChannels.lookup('4980')
        self.assertEqual(channel, ('5', '196'))


if __name__ == '__main__':
    unittest.main()
```

**Comment by johncooler** [comment]
Hi @alfrix, I fixed a trouble with type conversion, now it should work

**Comment by alfrix** [comment]
close but still not the same, as the division will create a floating point number

in python this is true:
int(12.0) == 12.0
and that will result in 'Channel 12.0'

i think this can be useful and further simplified, thank you for the effort

**Comment by johncooler** [comment]
okay, one simple fix and it would work

why you closed it?

**Comment by johncooler** [comment]
you literally steal the code
son of a bitch

**Comment by alfrix** [comment]
> you literally steal the code son of a bitch

i don't understand your hostility, i'm sorry that you feel this way, code re-writes are very common in opensource, your code had quite a few problems and i took the idea of dividing by 5 and rewrote it, trying to avoid type conversion issues like failure to convert to number, used float since is the most tolerant to convert to string without issues, simplified the chained expressions and avoided the unnecesary creation of variables, and casted int on return to avoid returning decimals in the string as channel numbers don't have decimals. i believe the issue  may have been that i forgot to add you as co-author ? if that is the case i'm sorry, you set out this to improve KS and you did, and for that i want to thank you

**Comment by johncooler** [comment]
>  i believe the issue may have been that i forgot to add you as co-author ? if that is the case i'm sorry, you set out this to improve KS and you did, and for that i want to thank you

YES! I'm not a co-author and it's horrible
there is no problem in rewriting before merging, but I want to have merged PR's in statistic for portfolio
even for such simple commits

**Comment by johncooler** [comment]
okay, nevermind, at least that pasta with if-elif does not exist anymore

**Pull request closed without merging**
