### PR TITLE
camera: relative url support close #1086

### LINKED ISSUE #1086: [BUG] Relative moonraker webcam url doesn't work
### What happened?

When setting up a webcam in moonraker the documentation states that the url to the webcam stream can be relative: https://moonraker.readthedocs.io/en/latest/configuration/#webcam

KlipperScreen fails to open a relative webcam stream but works fine when the camera stream url is absolute

### What did you expect to happen instead?

Camera should work as relative urls work perfectly in mainsail

### How to reproduce this bug?

* Set a webcam stream url in moonraker.conf to `/webcam/?action=stream`
* Open camera on klipperscreen
* Error: file: Cannot open file '/webcam/?action=stream'

### Additional information:

_No response_

### Log output

```shell
sie 18 19:01:49 server KlipperScreen-start.sh[14926]: 2023-08-18 19:01:49,180 [screen.py:attach_panel()] - Current panel hierarchy: main_menu > more > camera
sie 18 19:01:49 server KlipperScreen-start.sh[14926]: 2023-08-18 19:01:49,180 [camera.py:play()] - video filters: rotate:0.0
sie 18 19:01:49 server KlipperScreen-start.sh[14926]: 2023-08-18 19:01:49,211 [camera.py:play()] - Camera URL: /webcam/?action=stream
sie 18 19:01:49 server KlipperScreen-start.sh[14926]: 2023-08-18 19:01:49,222 [camera.py:log()] - [error] file: Cannot open file '/webcam/?action=stream': Nie ma takiego pliku ani katalogu
sie 18 19:01:49 server KlipperScreen-start.sh[14926]: 2023-08-18 19:01:49,224 [camera.py:log()] - [error] stream: Failed to open /webcam/?action=stream.
```

### LINKED ISSUE #1092: "No Xvideo support found." message when exiting from webcam-viewer
### What happened?

Exiting from the webcam-viewer, for a fraction of second the system displays the error message "No Video support found."

### What did you expect to happen instead?

Return to the Configuration menu without errors.

### How to reproduce this bug?

1) Go to the Webcam in the Configuration panel;
2) Exit from the webcam-viewer by tapping on the screen;
3) See error "No Xvideo support found." in the upper portion of the screen.

### Additional information:

5c94a7fd-669e-4b57-b175-77eacea24449

### Log output

```shell
2023-08-20 22:47:55,016 [screen.py:attach_panel()] - Current panel hierarchy: main_menu > actions > camera
2023-08-20 22:47:55,016 [camera.py:play()] - video filters: rotate:0.0
2023-08-20 22:47:55,043 [camera.py:play()] - Camera URL: http://10.10.10.103/webcam/?action=stream
2023-08-20 22:47:55,099 [camera.py:log()] - [warn] lavf: This format is marked by FFmpeg as having no timestamps!
2023-08-20 22:47:55,100 [camera.py:log()] - [warn] lavf: FFmpeg will likely make up its own broken timestamps. For
2023-08-20 22:47:55,101 [camera.py:log()] - [warn] lavf: video streams you can correct this with:
2023-08-20 22:47:55,101 [camera.py:log()] - [warn] lavf:     --no-correct-pts --fps=VALUE
2023-08-20 22:47:55,102 [camera.py:log()] - [warn] lavf: with VALUE being the real framerate of the stream. You can
2023-08-20 22:47:55,103 [camera.py:log()] - [warn] lavf: expect seeking and buffering estimation to be generally
2023-08-20 22:47:55,103 [camera.py:log()] - [warn] lavf: broken as well.
2023-08-20 22:47:55,109 [camera.py:log()] - [info] cplayer:  (+) Video --vid=1 (mjpeg)
2023-08-20 22:47:55,235 [camera.py:log()] - [warn] vo/gpu/opengl: Suspected software renderer or indirect context.
2023-08-20 22:47:55,476 [camera.py:log()] - [warn] vo/gpu/opengl: Suspected software renderer or indirect context.
2023-08-20 22:47:55,570 [camera.py:log()] - [error] vo/xv: No Xvideo support found.
2023-08-20 22:47:55,660 [camera.py:log()] - [warn] vo/x11: Warning: this legacy VO has bad performance. Consider fixing your graphics drivers, or not forcing the x11 VO.
2023-08-20 22:47:55,676 [camera.py:log()] - [warn] ffmpeg: swscaler: deprecated pixel format used, make sure you did set range correctly
2023-08-20 22:47:55,698 [camera.py:log()] - [info] cplayer: VO: [x11] 640x480 yuv444p
2023-08-20 22:47:56,276 [screen.py:_menu_go_back()] - #### Menu go back
2023-08-20 22:47:56,316 [screen.py:attach_panel()] - Current panel hierarchy: main_menu > actions
2023-08-20 22:47:56,353 [menu.py:arrangeMenuItems()] - X > actions power
2023-08-20 22:47:56,382 [menu.py:arrangeMenuItems()] - X > actions spoolman
```

### PR DESCRIPTION
**Pull request by alfrix**
also close #1092

### CODE REVIEW

**Comment by sowa705** [comment]
Could you also update the docs regarding camera configuration? The moonraker camera update missed updating the docs to mention camera_url got depreciated

**Comment by alfrix** [comment]
you are correct, thank you

**Comment by Guilouz** [comment]
@alfrix Not working.

This is the log :

2023-08-20 01:20:57,671 [camera.py:play()] - camera URL is relative
2023-08-20 01:20:57,671 [camera.py:play()] - video filters: rotate:0.0
2023-08-20 01:20:57,699 [camera.py:play()] - Camera URL: 127.0.0.1/webcam/?action=stream
2023-08-20 01:20:57,715 [camera.py:log()] - [error] file: Cannot open file '127.0.0.1/webcam/?action=stream': No such file or directory
2023-08-20 01:20:57,724 [camera.py:log()] - [error] stream: Failed to open 127.0.0.1/webcam/?action=stream.
2023-08-20 01:20:57,740 [camera.py:log()] - [info] cplayer:

**Comment by Guilouz** [comment]
And there is also something wrong error message (popup) is displayed for half a second and disappears.

**Comment by Guilouz** [comment]
@alfrix 
Tested your last change, missing ':' in URL.

2023-08-20 18:33:40,470 [screen.py:attach_panel()] - Current panel hierarchy: main_menu > actions > camera
2023-08-20 18:33:40,470 [camera.py:play()] - camera URL is relative
2023-08-20 18:33:40,471 [camera.py:play()] - video filters: rotate:0.0
2023-08-20 18:33:40,489 [camera.py:play()] - Camera URL: http//127.0.0.1/webcam/?action=stream
2023-08-20 18:33:40,507 [camera.py:log()] - [error] file: Cannot open file 'http//127.0.0.1/webcam/?action=stream': No such file or directory
2023-08-20 18:33:40,515 [camera.py:log()] - [error] stream: Failed to open http//127.0.0.1/webcam/?action=stream.

**Comment by Guilouz** [comment]
Another issue: 

Exiting from the webcam-viewer, for a fraction of second the system displays the error message "No Xvideo support found."

**Comment by alfrix** [comment]
> @alfrix Tested your last change, missing ':' in URL.
> 
> 2023-08-20 18:33:40,470 [screen.py:attach_panel()] - Current panel hierarchy: main_menu > actions > camera 2023-08-20 18:33:40,470 [camera.py:play()] - camera URL is relative 2023-08-20 18:33:40,471 [camera.py:play()] - video filters: rotate:0.0 2023-08-20 18:33:40,489 [camera.py:play()] - Camera URL: http//127.0.0.1/webcam/?action=stream 2023-08-20 18:33:40,507 [camera.py:log()] - [error] file: Cannot open file 'http//127.0.0.1/webcam/?action=stream': No such file or directory 2023-08-20 18:33:40,515 [camera.py:log()] - [error] stream: Failed to open http//127.0.0.1/webcam/?action=stream.

i'm sorry personal life is getting me, thank you for testing, it should be fixed now

**Comment by Guilouz** [comment]
@alfrix No problem, you do already a great job.

URL fixed, error message "No Xvideo support found." message still present after exiting fullscreen.

Another question, I use camera-streamer and seem not working

Capture d’écran 2023-08-21 à 11 34 53

Is it a limitation ? Only /webcam/?action=stream is working on Klipperscreen.

**Comment by alfrix** [comment]
ERROR: Unsupported URL: http://127.0.0.1/webcam/webrtc

then it's probably not supported, unless it needs a different protocol like rtsp instead of http, idk i never bought a camera, all the testing was done using a sample video

**Pull request merged**
