### PR TITLE
Fix fullscreen issue when setting width or height in config for non-desktop machines

### PR DESCRIPTION
**Pull request by EmJay276**
Setting width and height in the config should result in a windowed screen, but it is only the case for desktop users. 
Fixes https://github.com/KlipperScreen/KlipperScreen/issues/1176 introduced via 8f07f21

### CODE REVIEW

**Comment by alfrix** [comment]
you are undoing the previous commit, i stand my ground no fullscreen under desktop environments and width is for development, fix your resolution issues

**Comment by EmJay276** [comment]
@alfrix this won't change any behaviour introduced in https://github.com/KlipperScreen/KlipperScreen/commit/8f07f2197ebd9c9cbc5dc62f3268a9215bdbd6e8 to the desktop environment, neither revert it. Just fixes the bug introduced.

`if 'XDG_CURRENT_DESKTOP' in os.environ` it will set the `self.width` and `self.height` if not set in the config => `self.width` and `self.height` are always set after `L133` `if 'XDG_CURRENT_DESKTOP' in os.environ`
```
       if 'XDG_CURRENT_DESKTOP' in os.environ:
            if not self.width:
                self.width = max(int(monitor.get_geometry().width * .5), 480)
            if not self.height:
                self.height = max(int(monitor.get_geometry().height * .5), 320)
```

This lines here will result in exactly the same than in https://github.com/KlipperScreen/KlipperScreen/commit/8f07f2197ebd9c9cbc5dc62f3268a9215bdbd6e8, because `self.width` and `self.height` are set, except this will be also the case `if 'XDG_CURRENT_DESKTOP' NOT in os.environ` but `self.width` or `self.height` set in the config. => Same behaviour like 0.3.5 without the Bug introduced in https://github.com/KlipperScreen/KlipperScreen/commit/8f07f2197ebd9c9cbc5dc62f3268a9215bdbd6e8
```
        if self.width or self.height:
            self.set_resizable(True)
            self.windowed = True
```

**Comment by EmJay276** [comment]
A different implementation with the same result would be

```python
        if 'XDG_CURRENT_DESKTOP' in os.environ or self.width or self.height:
            if not self.width:
                self.width = max(int(monitor.get_geometry().width * .5), 480)
            if not self.height:
                self.height = max(int(monitor.get_geometry().height * .5), 320)
```

But this will set the other one of `self.width` or `self.height` if only one was specified in the config.

**Comment by alfrix** [comment]
ok, but you shouldn't be workarounding like this

**Pull request merged**
